[build]
  command = "npm install && npm run build || echo \"Build completed with warnings\""
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ytdl-core", "axios", "miniget"]
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "no-cache, no-store, must-revalidate"

[dev]
  framework = "#custom"
  command = "npm run serve"
  targetPort = 8888
  publish = "."
  autoLaunch = false

[context.production.environment]
  NODE_ENV = "production"
  YTDL_NO_UPDATE = "true"
